### ISSUE TITLE
use overflow-x on tables?

### ISSUE THREAD

**Issue by jimgregory** [andrewh0/okcss#1]
You've done a really nice job on this framework.  The only problem I've found is wide tables become very compressed on small phones in portrait mode.  Have you considered changing the table's "width: 100%" attribute to "display:block; overlow-x: scroll"?

**Comment by andrewh0** [comment]
Hey there, thanks so much for raising this issue and for checking out **OK.css**!

I tried fixing this issue here: https://github.com/andrewh0/okcss/pull/2

**Comment by jimgregory** [comment]
Thanks!
