### ISSUE TITLE
Description list (dl/dt/dd) spacing bug + general (mostly delighted) feedback :)

### ISSUE THREAD

**Issue by hartwork** [andrewh0/okcss#4]
Hi @andrewh0,

I came here from https://github.com/dohliam/dropin-minimal-css — okcss is my top favorite across the whole list. So expectations to find "something ok" have definitely been exceeded! :smiley:  How can this be 1 star before me only?! :thinking: 

Before I spam you with multiple GitHub tickets unasked, let me combine one likely bug and general feedback (below) in one ticket here for a start — I'm happy to split more issues off, if desired.

I think the styling of `<dl>`/`<dt>`/`<dd>` is broken with regard to spacing, this doesn't look right:

![okcss_bug_dl](https://user-images.githubusercontent.com/1577132/117053512-595d3380-ad19-11eb-9f1b-cdf0d62179f1.png)

With this (likely sub-optimal) workaround of mine…

```
dt {
    margin-bottom: 0;
}

dl dt:nth-child(1n+2) {
    margin-top: 1.5ex;
}
```

…I get things to this state:

![okcss_good_dl](https://user-images.githubusercontent.com/1577132/117053551-62e69b80-ad19-11eb-93d2-9e2526060db7.png)

What do you think about this issue and direction for a fix?

Other small things I noticed:

- Visual:
  - The overall "page width" is a bit too narrow for big screens.  I think what Boostrap's class `container` does may be a better default, but it would need a closer look. Is the current width considered a key feature?
- Non-visual:
  - The readme could mention dependency normalize.css in particular, not just normalization in general. I was surprised to find normalize.css bundled under the hood *after* reading that text.
  - It would be nice to have a version in `ok.min.css` like `ok-1.2.3.min.css` for easy identification and support for a non-moving target. I will likely put it inside a Git repo without using a CDN and for that scenario the version would be great.
  - Dist file `ok.min.css` file mentions normalize.css and its license inside, but does not mention okcss, its version and license.  That would be nice.
  - (Have you tried putting `:ok:`/:ok: at the start of the GitHub repo description? I think it would look nice.)

What do you think?

Best, Sebastian

**Comment by andrewh0** [comment]
Thanks so much for the feedback, Sebastian! That means a lot. I had no idea that OK.css was featured in another repo (and that others were considering using it!). Glad you were able to find it.

---

I created issues for a couple of next steps:
- https://github.com/andrewh0/okcss/issues/5 Implement versioning, automatic releases
- https://github.com/andrewh0/okcss/issues/6 Include license in the CSS

Let's discuss the remaining feedback here and break out into separate issues as necessary.

> I think the styling of `<dl>`/`<dt>`/`<dd>` is broken with regard to spacing

Agreed. Great catch! I think I'd prefer it to look something more like how it's styled here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl. Your workaround comes pretty close.

![image](https://user-images.githubusercontent.com/2905455/117097831-9cbba000-ad21-11eb-80a2-3a8f27c4cd20.png)

> The overall "page width" is a bit too narrow for big screens.  I think what Boostrap's class `container` does may be a better default, but it would need a closer look. Is the current width considered a key feature?

The `max-width` of the `body` is intentionally set to `80ch` (80 characters). For context, this exceeds [the recommendation](http://webtypography.net/2.1.2) to make lines somewhere between 45 and 75 characters wide for comfortable reading. Here's another resource on [this guideline](https://www.smashingmagazine.com/2014/09/balancing-line-length-font-size-responsive-web-design/).

> The readme could mention dependency normalize.css in particular, not just normalization in general. I was surprised to find normalize.css bundled under the hood *after* reading that text.

Yes! I mentioned the normalize.css dependency on [the project page](https://okcss.netlify.app/), but realized that I wasn't linking to it from the README! I can add a note about normalize.css in the README as well.

> (Have you tried putting `:ok:`/:ok: at the start of the GitHub repo description? I think it would look nice.)

✅ Done!

Thanks again for all the feedback. Keep it coming!

**Comment by hartwork** [comment]
> Thanks so much for the feedback, Sebastian! That means a lot. I had no idea that OK.css was featured in another repo (and that others were considering using it!). Glad you were able to find it.
> 
> I created issues for a couple of next steps:
> 
>     * #5 Implement versioning, automatic releases
> 
>     * #6 Include license in the CSS

Cool! :+1: 

> > I think the styling of `<dl>`/`<dt>`/`<dd>` is broken with regard to spacing
> 
> Agreed. Great catch! I think I'd prefer it to look something more like how it's styled here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl. Your workaround comes pretty close.
> 
> ![image](https://user-images.githubusercontent.com/2905455/117097831-9cbba000-ad21-11eb-80a2-3a8f27c4cd20.png)

That's pretty close, and retains structure :+1: I'm looking forward to see the OK.css version of that. 

> The `max-width` of the `body` is intentionally set to `80ch` (80 characters). For context, this exceeds [the recommendation](http://webtypography.net/2.1.2) to make lines somewhere between 45 and 75 characters wide for comfortable reading. Here's another resource on [this guideline](https://www.smashingmagazine.com/2014/09/balancing-line-length-font-size-responsive-web-design/).

I understand your point and I do see an inherent conflict between good reading line length and vertical density, the ability to see more of the big picture rather than single words.  It just felt a bit weird to have about as much unused space as there is used one. I workaround it with `max-width: none;` for my very case yesterday, and users can always make the browser window as narrow as they like to get their personal ideal "page width", but maybe I'll revert it and you're just right :man_shrugging: 

> Yes! I mentioned the normalize.css dependency on [the project page](https://okcss.netlify.app/), but realized that I wasn't linking to it from the README! I can add a note about normalize.css in the README as well.

Cool! :+1: 

> > (Have you tried putting `:ok:`/ok at the start of the GitHub repo description? I think it would look nice.)
> 
> :white_check_mark: Done!

Nice! :+1: 

> Thanks again for all the feedback. Keep it coming!

Cool! One tiny icing on the cake thing where I'm not sure it's possible to be done in pure CSS entirely (but it may), is for headings with HTML anchors, I often want to copy the link to them so I imagine on hover to have an ¶ (pilcrow sign) appear on the right or left that of them that is an a-tag linking to the same heading anchor and hence makes the browser offer a copy-link entry in the context menu. You have probably seen it elsewhere to, not sure where exactly.

PS: This is where I have merged use of OK.css to the `master` branch by now: https://github.com/libexpat/libexpat/pull/475

**Comment by hartwork** [comment]
I just checked version 1.0.2 over here. The spacing after the `<dl>` doesn't seem right — this is how a `<p>`-`<dl>`-`<p>` sequence looks like over here:

![okcss_bug_102](https://user-images.githubusercontent.com/1577132/117551495-96d9fd80-b046-11eb-97c2-226a5e6d13c8.png)

I think it needs significantly more whitespace to not look broken. What do you think?

**Comment by andrewh0** [comment]
> I think it needs significantly more whitespace to not look broken. What do you think?

I think you're right! The `dl` element should have the same margin-bottom as `ol` and `ul`. Fixing now!

**Comment by hartwork** [comment]
1.0.3 looks better, thanks! :pray:
